#!/usr/bin/env bash

# ARG_POSITIONAL_SINGLE([task_number],[the task number to correct],[])
# ARG_POSITIONAL_SINGLE([solution],[path to solution file],[])
# ARG_POSITIONAL_SINGLE([test_script],[path to test file],[])
# ARG_POSITIONAL_SINGLE([source],[path to the tsv file of the data],[])
# ARG_POSITIONAL_SINGLE([target],[path to the tsv file to put data in],[])
# ARG_HELP([This script grade tasks.])
# ARGBASH_SET_INDENT([    ])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die()
{
    local _ret="${2:-1}"
    test "${_PRINT_HELP:-no}" = yes && print_help >&2
    echo "$1" >&2
    exit "${_ret}"
}


begins_with_short_option()
{
    local first_option all_short_options='h'
    first_option="${1:0:1}"
    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
# THE DEFAULTS INITIALIZATION - OPTIONALS


print_help()
{
    printf '%s\n' "This script grade tasks."
    printf 'Usage: %s [-h|--help] <task_number> <solution> <test_script> <source> <target>\n' "$0"
    printf '\t%s\n' "<task_number>: the task number to correct"
    printf '\t%s\n' "<solution>: path to solution file"
    printf '\t%s\n' "<test_script>: path to test file"
    printf '\t%s\n' "<source>: path to the tsv file of the data"
    printf '\t%s\n' "<target>: path to the tsv file to put data in"
    printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
    _positionals_count=0
    while test $# -gt 0
    do
        _key="$1"
        case "$_key" in
            -h|--help)
                print_help
                exit 0
                ;;
            -h*)
                print_help
                exit 0
                ;;
            *)
                _last_positional="$1"
                _positionals+=("$_last_positional")
                _positionals_count=$((_positionals_count + 1))
                ;;
        esac
        shift
    done
}


handle_passed_args_count()
{
    local _required_args_string="'task_number', 'solution', 'test_script', 'source' and 'target'"
    test "${_positionals_count}" -ge 5 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 5 (namely: $_required_args_string), but got only ${_positionals_count}." 1
    test "${_positionals_count}" -le 5 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 5 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
    local _positional_name _shift_for=$1
    _positional_names="_arg_task_number _arg_solution _arg_test_script _arg_source _arg_target "

    shift "$_shift_for"
    for _positional_name in ${_positional_names}
    do
        test $# -gt 0 || break
        eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
        shift
    done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash




#-------------------------GRADE SCRIPT -------------------------
# Based on https://github.com/Badr-1/scripts/tree/main/testing

# A script to auto-grade OSC Linux committee tasks

# Requirements
# Git
# bat (for syntax-highlighted file viewing)
# lsd (for enhanced directory listing)
# fzf (for interactive file selection)
# Bash

# Input: tsv file with the following schema:
# | Timestamp | Email Address	| Full name | Link to Task repo |

# Output: tsv file with the following schema:
# "| Name | Email | Github Link | Result |"

# Result can take three values:
# CORRECT
# INCORRECT
# NOTSUBMITTED

# Hardcoded Arguments
# task=3
# solution="commands.sh"
# test_script="demo/test.sh"
# source="demo/sample.tsv"
# target="demo/output.tsv"

# Color constants
YELLOW="\033[33m"
NORMAL="\033[0;39m"
RED="\033[31m"
GREEN="\033[32m"
bold=$(tput bold)
normal=$(tput sgr0)

# Function definitions
run_test() {
    "$_arg_test_script" "$_arg_solution"
    return $?
}

next_repo() {
    cd "$root"
    [ -n "$reponame" ] && rm -rf "$reponame"
    read -p "${bold}Press Enter to move to the next repo ${normal}"
}

write_result() {
    cd "$root"
    echo -ne "Result: "
    if [ $result = "NOTSUBMITTED" ]; then
        echo -e "${RED}Not Submitted${NORMAL}"
    elif [ $result = "INCORRECT" ]; then
        echo -e "${YELLOW}Incorrect${NORMAL}"
    elif [ $result = "CORRECT" ]; then
        echo -e "${GREEN}Correct${NORMAL}"
    fi
    echo -e "$name\t$email\t$github_link\t$result" >>"$_arg_target"
}

test_repo() {
    #timestamp=$(echo "$entry" | cut -f1)
    result=NOTSUBMITTED
    name=$(echo "$entry" | cut -f3)
    email=$(echo "$entry" | cut -f2)
    github_link=$(echo "$entry" | cut -f6)
    reponame="entry_$student"
    echo -e "${bold}Name:${normal} $name"
    echo -e "${bold}Email:${normal} $email"
    echo -e "${bold}GitHub Link:${normal} $github_link"
    echo -e "${bold}Repo Name:${normal} $reponame"

    git clone "$github_link" "$reponame"

    lsd "$reponame"
    read -rp "${bold}Pause to fix the repo if needed. Press Enter to continue${normal}"

    # Check if task folder is present
    path="$(find "$reponame" -maxdepth 1 -type d | grep "$_arg_task_number")"

    if [ ! -n $path ]; then
        echo -e "${bold}${RED}Session $_arg_task_number folder not found${NORMAL}${normal}"
        result=NOTSUBMITTED
        write_result
        return 1
    fi

    echo -e "${GREEN}Session folder found!${NORMAL} Navigating..."
    cd "$path"

    # Check if solution file is present
    if [ -f "$_arg_solution" ]; then
        echo -e "${GREEN}Solution file found!${NORMAL}"
    else
        lsd
        read -rp "${bold}Does the solution exist? (y/n): ${normal}" answer
        if [ $answer == 'y' ]; then
            wrong_name=$(find . -type f | fzf)
            mv "$wrong_name" "$_arg_solution"
        else
            echo -e "${bold}${RED}$_arg_solution not found${NORMAL}${normal}"
            result=NOTSUBMITTED
            write_result
            return 1
        fi
    fi

    # Run test script
    if run_test;  then
        echo -e "${bold}${GREEN}Solution auto-graded as correct${NORMAL}${normal}"
        result=CORRECT
        write_result
        return 0
    else
        # Print solution to check manually
        echo -e "${bold}${YELLOW}Auto-grading failed!${NORMAL}${normal}"
        read -rp "${bold}Press Enter to grade manually ${normal}" answer
	
	kitty .

        read -rp "${bold}Is the solution correct? (y/n): ${normal}" answer
        if [ $answer == 'y' ]; then
            echo -e "${bold}${GREEN}Solution manually graded as correct${NORMAL}${normal}"
            result=CORRECT
            write_result
            return 0

        else
            echo -e "${bold}${YELLOW}$_arg_solution is not correct${NORMAL}${normal}"
            result=INCORRECT
            write_result
            return 1
        fi
    fi

}

# Main

echo -e "Name\tEmail\tGithub Link\tResult" >"$_arg_target"

echo "Grading ${bold}task $_arg_task_number${normal}..."

if [ ! -e $_arg_source ]; then
    echo -e "${bold}${RED}Data sheet not found!${NORMAL}${normal}"
    exit 1
fi

root=$(pwd)

repos_number=$(wc -l <"$_arg_source")
echo "${bold}Number of repos: $repos_number${normal}"

if [ ! -e $_arg_test_script ]; then
    echo -e "${bold}${RED}Test script not found!${NORMAL}${normal}"
    exit 1
fi

read -p "${bold}Press Enter to start testing${normal}"

for student in $(seq 1 "$repos_number"); do
    entry=$(sed -n $((student + 1))p $_arg_source)
    echo -e "Grading repo ${bold}$((student))/$repos_number${normal}"
    test_repo
    next_repo
    echo -e "-------------------------------)"
done

echo -e "Grading complete! Results in ${bold}$_arg_target${normal}"
bat $_arg_target
exit 0
# ] <-- needed because of Argbash
